### ISSUE TITLE
Code - Método imprimir verificando saldo

### ISSUE THREAD

**Issue by ghost** [BrunaFerreira7/Source-Code-Inspection#36]
@LarissaNami 
Método imprimir da classe TicketMachine deveria apenas exibir status do saldo, ao inves de fazer a lógica, verificar e informar saldo.

**Comment by LarissaNami** [comment]
`package br.calebe.ticketmachine.core;

import br.calebe.ticketmachine.exception.PapelMoedaInvalidaException;
import br.calebe.ticketmachine.exception.SaldoInsuficienteException;
import java.util.Iterator;

/**
 *
 * @author Calebe de Paula Bianchini
 */
public class TicketMachine {

    protected int valor;
    protected int saldo;
    protected int[] papelMoeda = {2, 5, 10, 20, 50, 100};

    public TicketMachine(int valor) {
        this.valor = valor;
        this.saldo = 0;
    }

    public void inserir(int quantia) throws PapelMoedaInvalidaException {
        boolean achou = false;
        for (int i = 0; i < papelMoeda.length && !achou; i++) {
            if (papelMoeda[1] == quantia) {
                achou = true;
            }
        }
        if (!achou) {
            throw new PapelMoedaInvalidaException();
        }
        this.saldo += quantia;
    }

    public int getSaldo() {
        return saldo;
    }

    public Iterator<Integer> getTroco() {
       return null;
    }

    public int imprimir() throws SaldoInsuficienteException {
        if (saldo < valor) {
            throw new SaldoInsuficienteException();
        } else{
            System.out.println("saldo disponivel");
        }
        return saldo;
        
    }
}`

**Comment by LarissaNami** [comment]
O metódo imprimir da classe TicketMachine, apresenta somente o status do saldo.
361df8747c062caefb67701982d3e2ffd5e32b3d
